apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app: todo-api
spec:
  selector:
    app: todo-api  # Ce Service cible tous les pods avec l'étiquette app=todo-api
  ports:
    - protocol: TCP
      port: 80          # Port exposé par le Service
      targetPort: 3000  # Port de l'app dans le pod
  type: NodePort        # Accessible depuis l'extérieur du cluster
