name: Todo API CI

on:
  push:
    branches: [ "projet-docker" ]
  pull_request:
    branches: [ "projet-docker" ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    
    # On précise que toutes les commandes (run) s'exécutent dans le dossier du projet
    defaults:
      run:
        working-directory: ./SERGIO_WICRAMACHINE_TODO_API
        
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './SERGIO_WICRAMACHINE_TODO_API/package-lock.json'

      - name: Installation des dépendances
        run: npm ci

      - name: Lancement des tests unitaires
        run: npm run test
